# Generated by Django 4.2 on 2026-02-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='sequence',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
