# Generated by Django 4.2 on 2026-09-15 06:06

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0002_homebanner_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='We Are Leader In Industrial Market', max_length=300)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Description')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='key_management/')),
                ('name', models.CharField(max_length=200)),
                ('designation', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Description')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Description')),
                ('link', models.URLField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls display order on the page.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this person from the website.')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ourservice',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='image_2',
        ),
        migrations.AddField(
            model_name='ourservice',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Controls display order'),
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
