# Generated by Django 4.2 on 2026-09-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0003_compliancesection_keymanagement_mission_vision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='site_banner/')),
                ('link', models.URLField(blank=True, help_text='Optional click destination', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Site Banner',
                'verbose_name_plural': 'Site Banner',
            },
        ),
    ]
