# Generated by Django 4.2 on 2026-09-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0004_sitebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebanner',
            name='page_name',
            field=models.CharField(blank=True, help_text='URL slug, e.g. about, compliance, contact. Leave blank to apply to all pages.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitebanner',
            name='page_title',
            field=models.CharField(blank=True, help_text='Optional page title override', max_length=200, null=True),
        ),
    ]
