# Generated by Django 4.2 on 2026-09-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0005_sitebanner_page_name_sitebanner_page_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='map_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
