# Generated by Django 4.2 on 2026-09-17 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0006_alter_contactinfo_map_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitebanner',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sitebanner',
            name='link',
        ),
    ]
