# Generated by Django 4.2 on 2026-09-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0007_remove_sitebanner_image_remove_sitebanner_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalframework',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='legal_framework/'),
        ),
        migrations.AddField(
            model_name='sitebanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site_banner/'),
        ),
        migrations.AddField(
            model_name='sitebanner',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
