# Generated by Django 4.2 on 2026-09-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0008_legalframework_image_sitebanner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestinvestordata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='investor/'),
        ),
    ]
