# Generated by Django 4.2 on 2026-09-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0009_requestinvestordata_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestinvestordata',
            options={'verbose_name': 'Register as Investor', 'verbose_name_plural': 'Register as Investors'},
        ),
        migrations.AlterModelOptions(
            name='requestinvestormessage',
            options={'verbose_name': 'Register as Investor Message', 'verbose_name_plural': 'Register as Investor Messages'},
        ),
        migrations.AlterField(
            model_name='requestinvestordata',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
