# Generated by Django 4.2 on 2026-09-23 11:25

from django.db import migrations, models
import re


COORDS_RE = re.compile(r'!2d([0-9.]+)!3d([0-9.]+)')


def populate_directions_link(apps, schema_editor):
    ContactInfo = apps.get_model('zone', 'ContactInfo')
    for obj in ContactInfo.objects.filter(is_active=True):
        if obj.map_directions_link:
            continue
        if obj.map_link and 'maps/embed' in obj.map_link:
            match = COORDS_RE.search(obj.map_link)
            if match:
                lng, lat = match.group(1), match.group(2)
                obj.map_directions_link = (
                    f'https://www.google.com/maps/dir/?api=1&destination={lat},{lng}'
                )
                obj.save(update_fields=['map_directions_link'])


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0010_alter_requestinvestordata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='map_directions_link',
            field=models.URLField(blank=True, help_text="Regular Google Maps place/directions link (https://www.google.com/maps/place/... or /maps/dir/?api=1&destination=...). Used by the 'Direction' button. Must NOT be an embed url.", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='map_link',
            field=models.URLField(blank=True, help_text='Google Maps EMBED url (https://www.google.com/maps/embed?pb=...). Used only inside the map <iframe>.', max_length=500, null=True),
        ),
        migrations.RunPython(populate_directions_link, reverse_code=migrations.RunPython.noop),
    ]
