# Generated by Django 4.2 on 2026-09-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0011_contactinfo_map_directions_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestinvestormessage',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
