# Generated by Django 4.2 on 2026-09-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0012_requestinvestormessage_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keymanagement',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
