# Generated by Django 4.2 on 2026-09-24 08:28

from django.db import migrations


def populate_facilities(apps, schema_editor):
    Facility = apps.get_model('zone', 'Facility')
    facilities = [
        {
            'name': 'Site Grading',
            'description': 'Project land has already been segregated in different grade i.e. industrial plot, commercial plot, utility building, administrative buildings, amenities and others.',
            'order': 1,
        },
        {
            'name': 'Boundary Wall',
            'description': 'Entire project would be surrounded by 7,267 running feet of 12-feet high wall.',
            'order': 2,
        },
        {
            'name': 'Connectivity',
            'description': 'BEZ is located at industrial zone. It\'s adjacent to Dhaka-Tangail Highway (construction of 04 Lane is underway). The project is 1.5 km away from Turag river.',
            'order': 3,
        },
        {
            'name': 'Entrance',
            'description': 'The project can easily be accessible through 100 feet wide bituminous road from Dhaka-Tangail highway.',
            'order': 4,
        },
        {
            'name': 'Surface Drainage',
            'description': 'The drainage network and structure has been designed to discharge the heavy rain during the rainy season so that the project can be free from flooding.',
            'order': 5,
        },
        {
            'name': 'Water Demand',
            'description': 'Water demand has been forecasted as 35,000 m3 / day by using ground water only.',
            'order': 6,
        },
        {
            'name': 'Fire Fighting',
            'description': 'Water demand for firefighting has been calculated based on population and land area. Fire service office consists 18 persons with two fire fighting vehicles and equipment.',
            'order': 7,
        },
        {
            'name': 'Sewage System',
            'description': 'The sewerage system is planned to cater for the anticipated peak discharge requirements and to treat the waste to the required discharge standards. The estimation of the sewage shall vary depending upon the land use distribution.',
            'order': 8,
        },
        {
            'name': 'Central Effluent Treatment Plant (CETP)',
            'description': 'Around 200 m3 / hour capacity CETP would be installed with configuration of the genuine treatment framework for a CETP. It includes determination of option procedures in light of the prerequisite/capacity of individual treatment procedures to expel particular waste constituents.',
            'order': 9,
        },
        {
            'name': 'Sewage Treatment Plant (STP)',
            'description': 'Sewage treatment is the process of removing contaminants from wastewater, comprising of storm run-off, domestic sewage and primary treated effluent. It includes physical, chemical and biological processes to remove various contaminants. In this stage industries manage sewerage through soak well; STP will be prepared for extension portion in the near future.',
            'order': 10,
        },
        {
            'name': 'Solid Waste Management (SWM)',
            'description': 'SWM is one of the most essential services for maintaining the quality of life in economic zone and for ensuring better standards of health and sanitation. Source segregation should be made mandatory and due care has to be taken while planning the collection, transportation of waste within the site area. Users will be required to segregate their waste as per described categories and put in different size bins. Finally, the waste would be dumped outside of the economic zone by the authorized local authority.',
            'order': 11,
        },
        {
            'name': 'Power Supply System',
            'description': 'There is a dedicated electricity line of RAEB only for BEZ. Bay Economic Zone has its own substation for electricity supply. The capacity of the substation is 20 MW. Initially 5 MW has taken from the nearby REB 33 KV line for Infrastructure development purposes which may be upgraded to 20 MW as per the future demand of the unit investors. Considering the fall of national grid for routine maintenance purpose a 400 KVA diesel generator set will be installed in addition to the existing 400 KVA diesel generator.',
            'order': 12,
        },
        {
            'name': 'Gas Demand',
            'description': 'A 15 MW gas-based power plant would be constructed for sourcing the required power to entire economic zone. Around 3 MMCFD of gas is required to run the power plant. A tripartite agreement, in this regard, among BEZA, BEZ and TGTDCL has been signed for construction of required infrastructure facility to supply gas in the project.',
            'order': 13,
        },
        {
            'name': 'Landscaping',
            'description': 'Includes works associated with the landscaping within the EZ covering tree strips along the boundary, roads, public greenery etc. Sufficient land Area will be used for landscaping and Aesthetic beautification of the project area.',
            'order': 14,
        },
        {
            'name': 'Amenities',
            'description': 'Specialized infrastructure and essential support facilities will be developed within the Economic Zone to meet the operational and lifestyle requirements of occupant units, investors, employees, and visitors. Key amenities include: Medical Center, Fire Service & Emergency Response, Investor Club & Recreation Center, China Garden Restaurant & Bar, Super Shop & Convenience Store, Cafeteria, Banking & ATM Services, 24/7 Security Services, Transportation & Shuttle Service, Maintenance & Technical Support, Accommodation for Foreign Staff, Parking Facilities & Green Spaces, High Speed Internet Services.',
            'order': 15,
        },
    ]
    for f in facilities:
        Facility.objects.create(**f)


def populate_incentives(apps, schema_editor):
    Incentive = apps.get_model('zone', 'Incentive')
    incentives = [
        {'title': 'Corporate Income Tax Exemption for 10 Years', 'short_description': 'Unit investors enjoy 10 years of corporate income tax exemption.', 'order': 1},
        {'title': 'Exemption from Dividend Tax', 'short_description': 'Dividend income is exempt from tax for unit investors.', 'order': 2},
        {'title': 'Duty Free Import of Raw Materials', 'short_description': 'Raw materials can be imported duty-free for manufacturing operations.', 'order': 3},
        {'title': 'Duty Free Import of Capital Machineries', 'short_description': 'Capital machinery imports are exempt from customs duties.', 'order': 4},
        {'title': '20% Sale of Finished Products to DTA', 'short_description': 'Up to 20% of finished products can be sold to the Domestic Tariff Area.', 'order': 5},
        {'title': 'Exemption of VAT on All Utility Services', 'short_description': 'All utility services (electricity, gas, water) are VAT-exempt.', 'order': 6},
        {'title': 'Exemption of Income Tax for Expatriates', 'short_description': 'Foreign expatriate employees enjoy income tax exemption.', 'order': 7},
        {'title': 'Duty Exemption on Export', 'short_description': 'Export products are exempt from export duties.', 'order': 8},
        {'title': 'Foreign Investors Free to Enter into JV', 'short_description': 'Foreign investors can freely enter into joint ventures without restrictions.', 'order': 9},
        {'title': 'Tax Exemption on Royalties, Technical Fees etc.', 'short_description': 'Royalties and technical service fees are tax-exempt.', 'order': 10},
        {'title': 'Tax Exemption on Capital Gains from Transfer of Shares', 'short_description': 'Capital gains from share transfers are exempt from tax.', 'order': 11},
        {'title': 'No Ceiling of FDI', 'short_description': 'No upper limit on Foreign Direct Investment.', 'order': 12},
        {'title': 'Repatriation of Dividend Earned Against Investment', 'short_description': 'Dividends earned can be fully repatriated without restrictions.', 'order': 13},
    ]
    for inc in incentives:
        Incentive.objects.create(**inc)


def reverse_populate(apps, schema_editor):
    Facility = apps.get_model('zone', 'Facility')
    Incentive = apps.get_model('zone', 'Incentive')
    Facility.objects.all().delete()
    Incentive.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0014_facility_incentive'),
    ]

    operations = [
        migrations.RunPython(populate_facilities, reverse_populate),
        migrations.RunPython(populate_incentives, reverse_populate),
    ]