# Generated by Django 4.2 on 2026-09-24 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0015_populate_facilities_incentives'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacilitiesIncentives',
        ),
    ]
