# Generated by Django 4.2 on 2026-09-24 09:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0016_remove_facilities_incentives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentive',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
