# Generated by Django 4.2 on 2026-09-24 09:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0017_alter_incentive_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
