# Generated by Django 4.2 on 2026-09-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0018_alter_facility_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('caption', models.CharField(blank=True, help_text='Optional caption shown on the image overlay', max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photo_gallery/')),
                ('visit_date', models.DateField(blank=True, help_text='Date of the visit (optional)', null=True)),
                ('visitor_name', models.CharField(blank=True, help_text='Name of the investor/visitor (optional)', max_length=200, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls display order on the page.')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Photo Gallery Item',
                'verbose_name_plural': 'Photo Gallery',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
