# Generated by Django 4.2 on 2026-09-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0019_photogallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photogallery',
            options={},
        ),
        migrations.RemoveField(
            model_name='photogallery',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='photogallery',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='photogallery',
            name='order',
        ),
        migrations.RemoveField(
            model_name='photogallery',
            name='visit_date',
        ),
        migrations.RemoveField(
            model_name='photogallery',
            name='visitor_name',
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='title',
            field=models.CharField(blank=True, default='We Are Leader In International Market', max_length=300, null=True),
        ),
    ]
