# Generated by Django 4.2 on 2026-09-27 08:52

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0020_alter_photogallery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='jv_details',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Rich text shown in the footer Joint Venture column.', null=True, verbose_name='Joint Venture Details'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='jv_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='jv_whatsapp',
            field=models.CharField(blank=True, help_text='e.g. +8801709995677', max_length=30, null=True),
        ),
    ]
