# Generated by Django 4.2 on 2026-09-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0021_contactinfo_jv_details_contactinfo_jv_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='background_video',
            field=models.FileField(blank=True, null=True, upload_to='Carousel/videos/'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='map_link',
            field=models.URLField(blank=True, help_text='Google Maps EMBED url (https://www.google.com/maps/embed?pb=...). Used only inside the map iframe.', max_length=500, null=True),
        ),
    ]
