# Generated by Django 4.2 on 2026-09-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0022_homebanner_background_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebanner',
            name='background_video',
            field=models.FileField(blank=True, null=True, upload_to='site_banner/videos/'),
        ),
    ]
