"""
Django settings for economic_zone project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ki^xe(gu0-(aky0f$2-178%sk6cusx)5bmac8(b0_gk-fva$+9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '103.169.105.109',
]

CSRF_TRUSTED_ORIGINS = [
    'http://103.169.105.109:7777',
]

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',
    'ckeditor_uploader',
    'zone',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.zoho.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
EMAIL_HOST_USER = 'info@bayeconomiczone.com'
EMAIL_HOST_PASSWORD = 'gzQQ ryd4 bBi6'
DEFAULT_FROM_EMAIL = 'info@bayeconomiczone.com'

ROOT_URLCONF = 'economic_zone.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'temp'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'zone.context_processors.site_banner',
            ],
        },
    },
]

WSGI_APPLICATION = 'economic_zone.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'economic_zone_test_db',
        'USER': 'economic_test',
        'PASSWORD': 'Eco@12345!',
        'HOST': 'localhost',  # Or your database host (e.g., '127.0.0.1')
        'PORT': '5432',        # Default PostgreSQL port
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# ======================
# STATIC FILES
# ======================
STATIC_URL = '/static/'

# Development time static files
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Production collectstatic output
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ======================
# MEDIA FILES
# ======================
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-navy",
    "accent": "accent-navy",
    "navbar": "navbar-navy navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-olive",
    "sidebar_nav_small_text": True,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "lumen",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": False
}

JAZZMIN_SETTINGS = {
    "site_title": "Economic Zone Admin",
    "site_header": "Economic Zone Admin",
    "site_logo": "images/logo.png",
    "welcome_sign": "Welcome to Economic Zone Admin",
    "copyright": "Economic Zone",
    "search_model": "account.User",
    "user_avatar": 'profile_picture',
    "icons": {
        "account": "fas fa-users-cog",
        "account.user": "fas fa-users-cog",
        "account.TempUserBeforeActive": "fas fa-star-half",

        "home.BannerSliderHome": "fas fa-sliders-h",
        "home.OurCollection": "fas fa-inbox",
        "home.FeaturedProduct": "fas fa-splotch",
        "home.LatestArrival": "fas fa-calendar-week",
        "home.ShopOurBrand": "fas fa-sliders-h",
        "home.BestSellerProduct": "fas fa-calendar-check",
        "home.BestSellerBrand": "fas fa-splotch",
        "home.GiftVoucher": "fab fa-microblog",
        "home.SocialMedia": "fas fa-icons",
        "home.MetaData": "fas fa-cloud-meatball",

        "coupons.Coupon": "fas fa-calendar-week",

        "customer.Address": "fas fa-address-card",
        "customer.Login": "fas fa-icons",
        "customer.Loyalty": "fas fa-star",
        "customer.Registration": "fas fa-puzzle-piece",

        "order.ShopCart": "fas fa-graduation-cap",
        "order.Order": "fas fa-subscript",
        "order.OrderProduct": "far fa-star",
        "order.Payment": "fas fa-money-bill-wave-alt",
        "order.Refund": "fas fa-stream",

        "product.Category": "fab fa-slideshare",
        "product.Product": "fas fa-address-card",
        "product.Images": "fas fa-bell",
        "product.Comment": "fas fa-inbox",
        "product.CommentForm": "fas fa-money-bill-wave-alt",
        "product.Color": "fas fa-file-invoice",
        "product.Size": "fab fa-monero",
        "product.Variants": "fab fa-monero",

        "data.BayEmporiumPage": "fas fa-money-bill-wave-alt",
        "data.BayEmporiumData": "fas fa-money-bill-wave-alt",
        "data.CustomerCarePage": "fas fa-money-bill-wave-alt",
        "data.CustomerCareData": "fas fa-money-bill-wave-alt",
        "data.CustomerInfoPage": "fas fa-money-bill-wave-alt",
        "data.CustomerInfoPageData": "fas fa-money-bill-wave-alt",
        "data.FollowUsPage": "fas fa-money-bill-wave-alt",
        "data.FollowUsPageData": "fas fa-money-bill-wave-alt",

    },
    "show_ui_builder": True
}

# ckeditor upload path
CKEDITOR_UPLOAD_PATH = "uploads/"
# ckeditor upload path
CKEDITOR_UPLOAD_PATH = "uploads/"

CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono-lisa',
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Source', '-', 'Save', 'NewPage', 'Preview', 'Print'],
            ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo'],
            ['Find', 'Replace', '-', 'SelectAll', '-', 'Scayt'],
            ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton', 'HiddenField'],
            ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote'],
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe'],
            ['Styles', 'Format', 'Font', 'FontSize'],
            ['TextColor', 'BGColor'],
            ['Maximize', 'ShowBlocks', 'CodeSnippet'],
        ],
        'extraPlugins': ','.join([
            'uploadimage',
            'image2',
            'codesnippet',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'iframe',
            'table',
            'tableresize',
            'justify',
            'font',
            'colorbutton',
            'smiley',
        ]),
        'codeSnippet_theme': 'monokai_sublime',
        'height': 400,
        'width': '100%',
        'removeDialogTabs': 'image:advanced;link:advanced',
        'allowedContent': True,
        'forcePasteAsPlainText': False,
    }
}